spring.application.name=task-tracker-example
spring.profiles.default=memory
spring.profiles.group.production=persistence,secure,cached
server.address=127.0.0.1
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health
