CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    owner_name VARCHAR(100) NOT NULL,
    version BIGINT NOT NULL
);
ALTER TABLE tasks ADD COLUMN project_id BIGINT;
ALTER TABLE tasks ADD CONSTRAINT tasks_project_fk FOREIGN KEY (project_id) REFERENCES projects(id);
CREATE INDEX projects_owner_id ON projects(owner_name, id);
CREATE INDEX tasks_project_id ON tasks(project_id, id);
