package com.csfundamentals.example;
import java.sql.DriverManager;
import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class MigrationUpgradeTest {
    @Test void explicitBaselineUpgradesTheOldMilestoneWithoutLosingTasks() throws Exception {
        String url = "jdbc:h2:mem:upgrade;DB_CLOSE_DELAY=-1";
        try (var connection = DriverManager.getConnection(url, "sa", "")) {
            connection.createStatement().execute("CREATE TABLE tasks (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title VARCHAR(120) NOT NULL, completed BOOLEAN NOT NULL, version BIGINT NOT NULL)");
            connection.createStatement().execute("INSERT INTO tasks (title, completed, version) VALUES ('Keep me', FALSE, 0)");
        }
        Flyway migration = Flyway.configure().dataSource(url, "sa", "").baselineOnMigrate(true).baselineVersion("1").load();
        migration.migrate(); migration.validate();
        try (var connection = DriverManager.getConnection(url, "sa", "");
             var rows = connection.createStatement().executeQuery("SELECT title, project_id FROM tasks")) {
            assertTrue(rows.next()); assertEquals("Keep me", rows.getString(1)); assertNull(rows.getObject(2));
            assertFalse(rows.next());
        }
        assertEquals("2", migration.info().current().getVersion().getVersion());
    }
}
