export const CATEGORY_METADATA = {
  os: { glyph: '◆', shortLabel: 'OS', label: 'Operating Systems' },
  networking: { glyph: '⬡', shortLabel: 'NET', label: 'Computer Networks' },
  dbms: { glyph: '▤', shortLabel: 'DB', label: 'Database Management Systems' },
  'java-spring': { glyph: '◐', shortLabel: 'JAVA', label: 'Java & Spring' },
  aiml: { glyph: '✳', shortLabel: 'AI/ML', label: 'AI & Machine Learning' }
}

export const TOPIC_CATEGORY_MAP = {
  'process-management': 'os',
  'memory-management': 'os',
  'cpu-scheduling': 'os',
  synchronization: 'os',
  deadlocks: 'os',
  'file-systems': 'os',
  'io-systems': 'os',
  'disk-scheduling': 'os',
  'network-fundamentals': 'networking',
  'physical-layer-media': 'networking',
  'osi-model': 'networking',
  'data-link-layer': 'networking',
  'ip-subnetting': 'networking',
  'routing-algorithms': 'networking',
  'tcp-ip': 'networking',
  'tcp-congestion': 'networking',
  'transport-layer-protocols': 'networking',
  'application-layer': 'networking',
  'network-security': 'networking',
  'network-performance-qos': 'networking',
  'dbms-introduction': 'dbms',
  'dbms-architecture': 'dbms',
  'er-model': 'dbms',
  'relational-algebra-calculus': 'dbms',
  'sql-querying': 'dbms',
  'functional-dependencies-keys': 'dbms',
  'database-normalization': 'dbms',
  'dbms-indexing': 'dbms',
  'storage-raid-indexing': 'dbms',
  'transactions-acid': 'dbms',
  'concurrency-control': 'dbms',
  'query-optimization': 'dbms',
  'distributed-databases-cap': 'dbms',
  'java-execution-pipeline': 'java-spring',
  'java-memory-model': 'java-spring',
  'java-oop-pillars': 'java-spring',
  'java-static-final-records': 'java-spring',
  'jvm-gc': 'java-spring',
  'java-functional-lambdas': 'java-spring',
  'java-generics': 'java-spring',
  'java-collections-framework': 'java-spring',
  'java-hashmap-internals': 'java-spring',
  'java-streams-optional': 'java-spring',
  'java-reflection-exceptions': 'java-spring',
  'java-multithreading-concurrency': 'java-spring',
  'spring-bean-lifecycle': 'java-spring',
  'spring-mvc-lifecycle': 'java-spring',
  'jpa-hibernate-lifecycle': 'java-spring',
  'spring-batch-lifecycle': 'java-spring',
  'quartz-scheduler': 'java-spring',
  'design-patterns-solid': 'java-spring',
  'spring-boot-internals': 'java-spring',
  'spring-rest-api-design': 'java-spring',
  'spring-security': 'java-spring',
  'spring-caching-async': 'java-spring',
  'spring-testing-production': 'java-spring',
  'ml-fundamentals': 'aiml',
  'embeddings-vector-db': 'aiml',
  'rag-architecture': 'aiml',
  'model-serving': 'aiml',
  'llm-parameters': 'aiml',
  'feature-stores': 'aiml',
  'recommendation-systems': 'aiml'
}

export function getTopicCategory(topicId, fallback = 'os') {
  return TOPIC_CATEGORY_MAP[topicId] || fallback
}
